title: UX Wiki
email: popomonclub@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/ux-wiki' # the subpath of your site, e.g. /blog
url: 'http://ux-monster.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: popocreator
github_username: popocreator

# Build settings
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - gemfiles/
  #   - Gemfile
  #   - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
